import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@styles/globals.css'

import { Providers } from '@components/providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  /**
   * If you do not add suppressHydrationWarning to your <html>
   * you will get warnings because next-themes updates that element.
   * This property only applies one level deep, so it won't block
   * hydration warnings on other elements.
   *
   * The div with the class of "relative flex h-screen flex-col" is used to
   * fix the data-overlay-container="true" from NextUI that is causing the
   * layout to be broken.
   */
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`min-h-screen ${inter.className}`}>
        <Providers>
          <div className="relative flex h-screen flex-col">{children}</div>
        </Providers>
      </body>
    </html>
  )
}
